package com.appsdeveloperblog.reactive.ws.users.data;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.r2dbc.DataR2dbcTest;
import reactor.test.StepVerifier;

import static org.junit.jupiter.api.Assertions.*;

@DataR2dbcTest  // Makes it easier to test Spring Data Reactive repositories without creating a full Spring application context.
class UserRepositorySaveTest {

    @Autowired
    private UserRepository userRepository;

    @Test
    public void testSaveUser_withValidRequest_shouldSaveUserToDatabase() {

        // given
        UserEntity validUser = new UserEntity(
                null,                           // ID is auto-generated by the database upon successful save
                "Sergey",
                "Kargopolov",
                "test@test.com",
                "password123"
        );

        // when and then
        userRepository.save(validUser)              // Returns a Mono<UserEntity>
                .as(StepVerifier::create)           // Verify the result
                .expectNextMatches(savedUser -> savedUser.getId() != null &&
                        savedUser.getFirstName().equals(validUser.getFirstName()) &&
                        savedUser.getLastName().equals(validUser.getLastName()) &&
                        savedUser.getEmail().equals(validUser.getEmail()))
                .verifyComplete();                  // Confirms that the operation completed successfully
    }
}