spring.application.name=users
spring.r2dbc.url=r2dbc:h2:mem:///testDb
spring.r2dbc.username=test
spring.r2dbc.password=test

# Run schema script to initialize database for H2 embedded db (embedded is the default for H2, therefore, not strictly necessary)
spring.sql.init.mode=embedded

