spring.application.name=users
spring.r2dbc.url=r2dbc:h2:mem:///testDb
spring.r2dbc.username=test
spring.r2dbc.password=test

spring.sql.init.mode=embedded

# Validation error messages
server.error.include-binding-errors=always
server.error.include-message=always

# SQL query logging specific for H2 database with R2DBC
loging.level.io.r2dbc.h2=DEBUG

# General
logging.level.org.springframework.r2dbc=DEBUG

# 64 characters, https://onlinestringtools.com/generate-random-string
token.secret=HT5CU6gWd2a3nUGtH3nf6nrcucPWN6G0plIWxUzI1UizGs1XaI86pIgi6WFwjp9d

base-uri=http://localhost

